Bugfix: set slave_id of STATUSUPDATE.
To fix the following error:

EncodeError: Message mesos.internal.StatusUpdateAcknowledgementMessage is missing required fields: slave_id.value